<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>k</string>
	</array>
	<key>firstLineMatch</key>
	<string>^#!.*\bk\b</string>
	<key>name</key>
	<string>K4</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(if|while|return)\b</string>
			<key>name</key>
			<string>keyword.control.k4</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.k4</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\.</string>
					<key>name</key>
					<string>constant.character.escape.k4</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>^/\s*\S.*$</string>
			<key>name</key>
			<string>comment.line.k4</string>
		</dict>
		<dict>
			<key>match</key>
			<string> /.*$</string>
			<key>name</key>
			<string>comment.line.k4</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^/w*$</string>
			<key>end</key>
			<string>^\\\w*$</string>
			<key>name</key>
			<string>comment.line.block.k4</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(abs|acos|asin|atan|avg|bin|binr|by|cor|cos|cov|delete|dev|div|exec|exit|exp|from|from|getenv|in|insert|last|like|log|max|min|prd|select|setenv|sin|sqrt|ss|sum|tan|update|var|wavg|within|wsum|xexp)\b</string>
			<key>name</key>
			<string>keyword.operator.k4</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\.z\.D|\.z\.K|\.z\.T|\.z\.Z|\.z\.N|\.z\.P|\.z\.a|\.z\.b|\.z\.d|\.z\.exit|\.z\.f|\.z\.h|\.z\.i|\.z\.k|\.z\.l|\.z\.o|\.z\.pc|\.z\.pg|\.z\.ph|\.z\.pi|\.z\.po|\.z\.pp|\.z\.ps|\.z\.pw|\.z\.s|\.z\.t|\.z\.ts|\.z\.u|\.z\.vs|\.z\.w|\.z\.x|\.z\.z|\.z\.n|\.z\.p)\b</string>
			<key>name</key>
			<string>variable.language.k4</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>system call</string>
			<key>match</key>
			<string>^\\\w.*$</string>
			<key>name</key>
			<string>string.interpolated.k4</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>file</string>
			<key>match</key>
			<string>`:(\w|[/:.])*</string>
			<key>name</key>
			<string>constant.language.k4</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>file</string>
			<key>match</key>
			<string>`((\w|[/:.])(\w|[/:.])*)?</string>
			<key>name</key>
			<string>constant.language.k4</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.k4</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>function</string>
			<key>match</key>
			<string>(\.?[a-zA-Z]\w*):\s*[{]</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.k4</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>variable</string>
			<key>match</key>
			<string>(\.?[a-zA-Z](\w|\.)*)\s*[~=!@#$%^&amp;*-_+|,&lt;&gt;?]?::?</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>io/ipc</string>
			<key>match</key>
			<string>\b[01]:</string>
			<key>name</key>
			<string>constant.numeric.k4</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>timespan/timestamp</string>
			<key>match</key>
			<string>\b([0-9][0-9][0-9][0-9]\.[0-9][0-9]\.[0-9][0-9]|[0-9]+)D([0-9][0-9]([:][0-9][0-9]([:][0-9][0-9](\.[0-9]*))?)?)?\b</string>
			<key>name</key>
			<string>constant.numeric.k4</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>month/date/datetime</string>
			<key>match</key>
			<string>\b[0-9][0-9][0-9][0-9]\.[0-9][0-9](m|\.[0-9][0-9](T[0-9][0-9]:[0-9][0-9]([:][0-9][0-9](\.[0-9]*)?)?)?)\b</string>
			<key>name</key>
			<string>constant.numeric.k4</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>time</string>
			<key>match</key>
			<string>\b[0-9][0-9]:[0-9][0-9]([:][0-9][0-9](\.[0-9]|\.[0-9][0-9]|\.[0-9][0-9][0-9])?)?\b</string>
			<key>name</key>
			<string>constant.numeric.k4</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>guid</string>
			<key>match</key>
			<string>\b[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\b</string>
			<key>name</key>
			<string>constant.numeric.k4</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>bytes</string>
			<key>match</key>
			<string>\b0x[0-9a-fA-F]+\b</string>
			<key>name</key>
			<string>constant.numeric.k4</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>null/infinity</string>
			<key>match</key>
			<string>\b0[nNwW][cefghijmndzuvtp]?\b</string>
			<key>name</key>
			<string>constant.numeric.k4</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>boolean</string>
			<key>match</key>
			<string>\b[01]+b</string>
			<key>name</key>
			<string>constant.numeric.k4</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>float</string>
			<key>match</key>
			<string>\b[0-9]*[0-9.][0-9]*([eE]-?[0-9]+)?[ef]?</string>
			<key>name</key>
			<string>constant.numeric.k4</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>integer</string>
			<key>match</key>
			<string>\b[0-9]+[cefhijnptuv]?\b</string>
			<key>name</key>
			<string>constant.numeric.k4</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.k4</string>
	<key>uuid</key>
	<string>B1B752ED-CC3A-499C-9BC2-3EEDCD444C66</string>
</dict>
</plist>
